import type { RoadmapFeature, RoadmapStats, RoadmapCategory, Backer, Milestone } from '@/types/roadmap-voting';

/**
 * Roadmap Voting Data
 */

export const roadmapFeatures: RoadmapFeature[] = [
  // Completed Features
  {
    id: 'feature_1',
    title: 'Dark Mode Support',
    description: 'Add dark mode toggle with system preference detection and localStorage persistence.',
    category: 'feature',
    status: 'completed',
    votes: 156,
    targetAmount: 500,
    currentAmount: 620,
    estimatedHours: 8,
    complexity: 'medium',
    tags: ['ui', 'accessibility', 'css'],
    author: 'Alex Chen',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    completedAt: '2026-02-15T00:00:00Z',
    voters: ['user_1', 'user_2', 'user_3'],
    comments: [],
    updates: [
      {
        id: 'update_1',
        featureId: 'feature_1',
        type: 'release',
        message: 'Dark mode is now live! Toggle it in the header.',
        authorId: 'dev',
        createdAt: '2026-02-15T00:00:00Z',
      },
    ],
  },
  {
    id: 'feature_2',
    title: 'Search Functionality',
    description: 'Implement full-text search across blog posts, journal entries, and projects.',
    category: 'feature',
    status: 'completed',
    votes: 234,
    targetAmount: 800,
    currentAmount: 950,
    estimatedHours: 16,
    complexity: 'large',
    tags: ['search', 'performance', 'ux'],
    author: 'Sarah Miller',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
    completedAt: '2026-02-20T00:00:00Z',
    voters: ['user_1', 'user_4', 'user_5'],
    comments: [],
    updates: [],
  },

  // In Progress
  {
    id: 'feature_3',
    title: 'Interactive Knowledge Graph',
    description: 'Visual graph showing connections between blog posts, technologies, and concepts.',
    category: 'feature',
    status: 'in-progress',
    votes: 189,
    targetAmount: 1200,
    currentAmount: 1350,
    estimatedHours: 24,
    complexity: 'xl',
    tags: ['visualization', 'd3.js', 'graph'],
    author: 'DevTeam Inc.',
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
    voters: ['user_2', 'user_6'],
    comments: [],
    updates: [
      {
        id: 'update_2',
        featureId: 'feature_3',
        type: 'progress',
        message: 'Graph rendering engine complete. Working on data connections.',
        authorId: 'dev',
        createdAt: '2026-03-10T00:00:00Z',
        metadata: { prUrl: 'https://github.com/pr/42' },
      },
    ],
  },

  // Voting
  {
    id: 'feature_4',
    title: 'AI Chat Assistant',
    description: 'Integrate an AI assistant that can answer questions about my experience, projects, and skills.',
    category: 'feature',
    status: 'voting',
    votes: 312,
    targetAmount: 2000,
    currentAmount: 1450,
    estimatedHours: 40,
    complexity: 'xl',
    tags: ['ai', 'chat', 'llm'],
    author: 'TechCorp',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    voters: ['user_3', 'user_7', 'user_8'],
    comments: [],
    updates: [],
  },
  {
    id: 'feature_5',
    title: 'RSS Feed Improvements',
    description: 'Add full content to RSS feeds, custom styling, and podcast support.',
    category: 'improvement',
    status: 'voting',
    votes: 87,
    targetAmount: 300,
    currentAmount: 180,
    estimatedHours: 4,
    complexity: 'small',
    tags: ['rss', 'content', 'podcast'],
    author: 'John Doe',
    createdAt: '2026-03-05T00:00:00Z',
    updatedAt: '2026-03-14T00:00:00Z',
    voters: ['user_9'],
    comments: [],
    updates: [],
  },
  {
    id: 'feature_6',
    title: 'Performance Optimization',
    description: 'Improve Lighthouse scores: optimize images, lazy load components, reduce bundle size.',
    category: 'performance',
    status: 'voting',
    votes: 156,
    targetAmount: 600,
    currentAmount: 420,
    estimatedHours: 12,
    complexity: 'medium',
    tags: ['performance', 'lighthouse', 'optimization'],
    author: 'Emma Wilson',
    createdAt: '2026-03-08T00:00:00Z',
    updatedAt: '2026-03-16T00:00:00Z',
    voters: ['user_10', 'user_11'],
    comments: [],
    updates: [],
  },
  {
    id: 'feature_7',
    title: 'Security Headers',
    description: 'Add CSP, HSTS, and other security headers for better protection.',
    category: 'security',
    status: 'voting',
    votes: 67,
    targetAmount: 400,
    currentAmount: 150,
    estimatedHours: 4,
    complexity: 'small',
    tags: ['security', 'headers', 'csp'],
    author: 'Security First',
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    voters: ['user_12'],
    comments: [],
    updates: [],
  },

  // Proposed
  {
    id: 'feature_8',
    title: 'Multi-language Support',
    description: 'Add i18n support for English and Vietnamese content.',
    category: 'feature',
    status: 'proposed',
    votes: 45,
    targetAmount: 1000,
    currentAmount: 0,
    estimatedHours: 20,
    complexity: 'large',
    tags: ['i18n', 'translation', 'accessibility'],
    author: 'Global User',
    createdAt: '2026-03-12T00:00:00Z',
    updatedAt: '2026-03-12T00:00:00Z',
    voters: [],
    comments: [],
    updates: [],
  },
  {
    id: 'feature_9',
    title: 'Comment System',
    description: 'Add comments to blog posts using a self-hosted solution (not Disqus).',
    category: 'feature',
    status: 'proposed',
    votes: 78,
    targetAmount: 500,
    currentAmount: 0,
    estimatedHours: 12,
    complexity: 'medium',
    tags: ['comments', 'engagement', 'database'],
    author: 'Community Fan',
    createdAt: '2026-03-14T00:00:00Z',
    updatedAt: '2026-03-14T00:00:00Z',
    voters: [],
    comments: [],
    updates: [],
  },
];

export const roadmapStats: RoadmapStats = {
  totalFeatures: 24,
  completedFeatures: 12,
  totalVotes: 1324,
  totalFunded: 15670,
  activeVoters: 89,
  averageCompletionTime: '2.5 weeks',
};

export const roadmapCategories: RoadmapCategory[] = [
  {
    id: 'feature',
    name: 'Features',
    color: 'green',
    icon: '✨',
    description: 'New functionality',
    featureCount: 8,
  },
  {
    id: 'improvement',
    name: 'Improvements',
    color: 'blue',
    icon: '📈',
    description: 'Enhancements to existing features',
    featureCount: 5,
  },
  {
    id: 'bugfix',
    name: 'Bug Fixes',
    color: 'red',
    icon: '🐛',
    description: 'Bug fixes and stability',
    featureCount: 4,
  },
  {
    id: 'documentation',
    name: 'Documentation',
    color: 'yellow',
    icon: '📚',
    description: 'Docs and guides',
    featureCount: 3,
  },
  {
    id: 'performance',
    name: 'Performance',
    color: 'purple',
    icon: '⚡',
    description: 'Speed and optimization',
    featureCount: 3,
  },
  {
    id: 'security',
    name: 'Security',
    color: 'orange',
    icon: '🔒',
    description: 'Security improvements',
    featureCount: 1,
  },
];

export const topBackers: Backer[] = [
  {
    id: 'backer_1',
    name: 'TechCorp Inc.',
    avatarUrl: 'https://github.com/techcorp.png',
    totalBacked: 5000,
    featuresBacked: ['feature_1', 'feature_2', 'feature_3', 'feature_4'],
    votes: 4,
    rank: 'legendary',
    badges: ['🏆 Top Backer', '💎 Platinum', '🚀 Early Adopter'],
    joinedAt: '2026-01-01',
  },
  {
    id: 'backer_2',
    name: 'Alex Chen',
    avatarUrl: 'https://github.com/alexchen.png',
    totalBacked: 1500,
    featuresBacked: ['feature_1', 'feature_3'],
    votes: 2,
    rank: 'platinum',
    badges: ['💎 Platinum', '🚀 Early Adopter'],
    joinedAt: '2026-01-15',
  },
  {
    id: 'backer_3',
    name: 'Sarah Miller',
    avatarUrl: 'https://github.com/sarahmiller.png',
    totalBacked: 950,
    featuresBacked: ['feature_2'],
    votes: 1,
    rank: 'gold',
    badges: ['🥇 Gold'],
    joinedAt: '2026-02-01',
  },
  {
    id: 'backer_4',
    name: 'DevTeam Labs',
    avatarUrl: null,
    totalBacked: 600,
    featuresBacked: ['feature_4'],
    votes: 1,
    rank: 'gold',
    badges: ['🥇 Gold'],
    joinedAt: '2026-02-15',
  },
  {
    id: 'backer_5',
    name: 'Emma Wilson',
    avatarUrl: 'https://github.com/emmawilson.png',
    totalBacked: 420,
    featuresBacked: ['feature_6'],
    votes: 1,
    rank: 'silver',
    badges: ['🥈 Silver'],
    joinedAt: '2026-03-01',
  },
];

export const milestones: Milestone[] = [
  {
    id: 'milestone_1',
    title: 'Q1 2026 Release',
    description: 'Core features for Q1: Dark mode, search, and knowledge graph.',
    targetDate: '2026-03-31',
    features: ['feature_1', 'feature_2', 'feature_3'],
    progress: 67,
    isCompleted: false,
  },
  {
    id: 'milestone_2',
    title: 'Q2 2026 Release',
    description: 'AI integration and performance improvements.',
    targetDate: '2026-06-30',
    features: ['feature_4', 'feature_6'],
    progress: 15,
    isCompleted: false,
  },
  {
    id: 'milestone_3',
    title: 'Community Features',
    description: 'Comments, multi-language support, and engagement features.',
    targetDate: '2026-09-30',
    features: ['feature_8', 'feature_9'],
    progress: 0,
    isCompleted: false,
  },
];

export const votingTiers = [
  { amount: 10, votes: 1, name: 'Supporter', perk: '1 vote' },
  { amount: 25, votes: 3, name: 'Bronze', perk: '3 votes + name in credits' },
  { amount: 50, votes: 5, name: 'Silver', perk: '5 votes + priority support' },
  { amount: 100, votes: 12, name: 'Gold', perk: '12 votes + feature request' },
  { amount: 500, votes: 75, name: 'Platinum', perk: '75 votes + 1:1 call' },
  { amount: 1000, votes: 200, name: 'Legendary', perk: '200 votes + co-creator credit' },
];
