name: Deploy Astro to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write     # 🔥 BẮT BUỘC để dùng OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::904610148329:role/github-deploy-role
          aws-region: ap-southeast-1   # đổi region của bạn

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://truongdq.com --delete

      - name: Verify AWS identity
        run: aws sts get-caller-identity
